/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-26 02:52:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head profile=\"http://www.w3.org/2005/10/profile\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"http://example.com/myicon.png\">\r\n");
      out.write("<title>camper.page3</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h1 {\r\n");
      out.write("\tcolor: #FFBF00\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section {\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".aside {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 15%;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write("#floatMenu {\r\n");
      out.write("position: absolute;\r\n");
      out.write("\tleft: 1500px;\r\n");
      out.write("\ttop: 700px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t// 기존 css에서 플로팅 배너 위치(top)값을 가져와 저장한다.\r\n");
      out.write("\tvar floatPosition = parseInt($(\"#floatMenu\").css('top'));\r\n");
      out.write("\t// 250px 이런식으로 가져오므로 여기서 숫자만 가져온다. parseInt( 값 );\r\n");
      out.write("\r\n");
      out.write("\t$(window).scroll(function() {\r\n");
      out.write("\t\t// 현재 스크롤 위치를 가져온다.\r\n");
      out.write("\t\tvar scrollTop = $(window).scrollTop();\r\n");
      out.write("\t\tvar newPosition = scrollTop + floatPosition + \"px\";\r\n");
      out.write("\r\n");
      out.write("\t\t/* 애니메이션 없이 바로 따라감\r\n");
      out.write("\t\t $(\"#floatMenu\").css('top', newPosition);\r\n");
      out.write("\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#floatMenu\").stop().animate({\r\n");
      out.write("\t\t\t\"top\" : newPosition\r\n");
      out.write("\t\t}, 500);\r\n");
      out.write("\r\n");
      out.write("\t}).scroll();\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#floatMenu\").stop().animate({\r\n");
      out.write("\t\"top\" : newPosition\r\n");
      out.write("}, {\r\n");
      out.write("\t'duration' : 500,\r\n");
      out.write("\t'easing' : 'easeInOutCubic',\r\n");
      out.write("\t'complete' : function() {\r\n");
      out.write("\t\tconsole.log('이동 완료하였습니다.');\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("   </script> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container pt-5\" id=\"upper\">\r\n");
      out.write("\t\t<div class=\"row justify-content-between\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><section style=\"width: 200px; height: 116px; background-image: url('/myapp/resources/images/head.jpg');\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col d-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t<div class=\"social-media\">\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0 d-flex\">Login</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\t\tid=\"ftco-navbar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"fa fa-bars\"></span> Menu\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<form action=\"#\" class=\"searchform order-lg-last\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group d-flex\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control pl-3\" placeholder=\"검색\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" placeholder=\"\" class=\"form-control search\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-search\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"home\" class=\"nav-link\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page2\" class=\"nav-link\">둘러보기</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page3\" class=\"nav-link\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page4\" class=\"nav-link\">예약 및 대여</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page5\" class=\"nav-link\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page99\" class=\"nav-link\">관리자</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("\t\tstyle=\"background-image: url('/myapp/resources/images/campmain.PNG');\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row no-gutters slider-text align-items-end\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("\t\t\t\t\t<p class=\"breadcrumbs mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mr-2\"><a href=\"index.html\">메인 <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-arrow-forward\"></i></a></span> <span>이용안내 <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ion-ios-arrow-forward\"></i></span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-0 bread\">이용안내</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<nav class=\"nav\">nav</nav>\r\n");
      out.write("\t<aside class=\"aside\">aside\t\r\n");
      out.write("\t<ul id=\"floatMenu\">\r\n");
      out.write("\t\t\t<li><a href=\"#upper\"><div style=\"color:black; text-align:center; width:186px; height: 43px; background-image: url('/myapp/resources/images/ani.png')\"><strong>이용안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#campinfo\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/ani.png')\"><strong>캠핑장 이용안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#pikinfo\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/ani.png')\"><strong>피크닉 이용안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#timeNpay\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/ani.png')\"><strong>이용시간 및 요금안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#tip\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/ani.png')\"><strong>준수사항 및 팁</strong></div></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("\t<section class=\"section\">\r\n");
      out.write("\t\t<article id=\"campinfo\">\r\n");
      out.write("\t\t\t<h1>캠핑장 이용안내</h1>\r\n");
      out.write("\t\t\t<hr align=\"left\">\r\n");
      out.write("\t\t\t<h2>캠핑장을 이용하려면...</h2>\r\n");
      out.write("\t\t\t<pre>Camper 캠핑장은 캠핑장 이용객을 \"피크닉 이용객\" 과 \"숙영자\" 로 구분하여 운영하고 있습니다.\r\n");
      out.write("텐트를 이용하지 않고 점심 혹은 저녁식사 등의 간단한 취사 및 바베큐 파티를 하는 경우와(피크닉 이용자)가\r\n");
      out.write("텐트를치시거나 임대 텐트를 예약하여 숙영을 하는 이용객(숙영자)을 구분하기 위함 입니다.\r\n");
      out.write("<span>이용시간 및 이용방법에는 차이가 없으며 숙영자의 경우 <strong><ins>예약</ins></strong>을 먼저 하셔야 합니다.</span>\r\n");
      out.write("\t\t\t\t</pre>\r\n");
      out.write("\t\t\t<h2>캠핑 이용객</h2>\r\n");
      out.write("\t\t\t캠핑장이용(숙영지 및 텐트이용)을 원하시는 분들은<strong><ins>\"사전예약\"</ins></strong>을 통해서\r\n");
      out.write("\t\t\t이용하시면 편리하게 이용하실 수 있습니다.\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>캠핑장은 이용 편의를 위해 입장료와 텐트 대여료가 함께 계산됩니다.</li>\r\n");
      out.write("\t\t\t\t<li>캠핑장은 가족텐트(<mark>B구역</mark>)지역과 개인텐트(<mark>C,D구역</mark>)지역으로\r\n");
      out.write("\t\t\t\t\t나뉘어 집니다.\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>캠핑장의 텐트 위치 가이드\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>임대 텐트지역 : B,C,D 구역 이용</li>\r\n");
      out.write("\t\t\t\t\t\t<li><strong>B,C,D(텐트)지역</strong> 모두 <b>사전예약 만 가능</b>합니다.</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- <img width=600 height=400 src=\"/resources/css/images/camp.PNG\"> -->\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 600px; height: 400px; background-image: url('/myapp/resources/images/camp.PNG');\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t<td>구역 위치도</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h2>주의하실 점</h2>\r\n");
      out.write("\t\t\t<ol type=\"1\">\r\n");
      out.write("\t\t\t\t<li>이용시 편의를 위해 캠핑장 <strong>출입팔찌</strong>를 드리며 캠핑장 이용이 마무리 되실때까지\r\n");
      out.write("\t\t\t\t\t착용하고<br> 계시면 캠핑장 안,밖 출입이 가능합니다. 다만 <strong>분실,미착용 시\r\n");
      out.write("\t\t\t\t\t\t입장권을 재구매</strong> 하셔야 하오<br> 니 주의해 주시기를 당부드립니다.\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>캠핑을 이용하신 경우 별도의 체크아웃 절차 없이 <b>익일 오전 09시 30분 까지 퇴영</b>하시면\r\n");
      out.write("\t\t\t\t\t됩니다.<br> 퇴장하시기 전 필히 <strong>대여용품 반납과 쓰레기 정리</strong>를 해주셔야\r\n");
      out.write("\t\t\t\t\t합니다.\r\n");
      out.write("\t\t\t\t\t<ol type=\"i\">\r\n");
      out.write("\t\t\t\t\t\t<li>쓰레기는 \"한강규격봉투(매표소 및 편의점 판매)\"를 사용하셔야 합니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li><string>음식물 쓰레기는 피크닉/캠핑 구역 중간 식수대에 비치된 바구니</string>에\r\n");
      out.write("\t\t\t\t\t\t\t버려주시면 됩니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>대여 물품 반납 후 신분증을 찾아가시면 됩니다.</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><b>미성년자 텐트 입장시 숙지사항</b> <legend>\r\n");
      out.write("\t\t\t\t\t\t<ol type=\"i\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>텐트 입장시 <b>숙박하는 모든 미성년자들의 보호자 자필동의서 </b>혹은<b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t부모님의 대면확인</b>이 필요합니다.<br> (동의서 미 제출 시 <strong>오후 10시\r\n");
      out.write("\t\t\t\t\t\t\t\t\t이전 강제퇴영조치</strong> 됩니다.)\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>법적 보호자를 동반하지 않은 <b>미성년자 혼숙은 절대불가</b> 합니다.\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</legend></li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 170px; background-image: url('/myapp/resources/images/4tent.PNG');\"></td>\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 170px; background-image: url('/myapp/resources/images/6tent.PNG');\"></td>\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 170px; background-image: url('/myapp/resources/images/mytent.PNG');\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t<td>4인용 텐트</td>\r\n");
      out.write("\t\t\t\t\t<td>6인용 텐트</td>\r\n");
      out.write("\t\t\t\t\t<td>개인용 텐트</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>숙영지인 텐트 지역은 <strong>전기사용(8000원) 가능</strong></li>\r\n");
      out.write("\t\t\t\t<li>대여텐트는 <strong>4인용과 6인용을 구분</strong>\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li>안전 및 편안한 숙영을 위해 텐트내 숙영 인원을 구분, 4인용, 6인용 으로 나누어져 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>텐트 대여 및 상세가격 안내는 <strong>이용시간 및 요금 안내를 참조</strong>하시기 바랍니다.\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article id=\"pikinfo\">\r\n");
      out.write("\t\t\t<h1>피크닉 이용안내</h1>\r\n");
      out.write("\t\t\t<hr align=\"left\">\r\n");
      out.write("\t\t\t<h2>피크닉 이용객</h2>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("텐트를 설치하지 않고 <strong>자유 이용공간(피크닉존)에서 점심, 저녁 등의 간단한 취사 및 바베큐 파티를\r\n");
      out.write("원하시는 경우 예약없이 당일 이용이 가능</strong> 합니다.\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("예약없이 당일 방문통해 이용하실 수 있으며 당일 입장권 구매 후 <strong>텐트설치없이 캠핑장내 자유 이용\r\n");
      out.write("공간(피크닉지역)을 이용</strong>하시면 됩니다.\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("피크닉을 위한 캠핑장은 <b>오전 10시 30분 부터 익일오전 09시 30분 까지</b> 이용하실 수 있으며 캠핑장내 피크닉\r\n");
      out.write("장소의 비어있는 공간을 이용하시면 됩니다.\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 170px; background-image: url('/myapp/resources/images/market1.PNG');\"></td>\r\n");
      out.write("\t\t\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 170px; background-image: url('/myapp/resources/images/market2.PNG');\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">캠핑장 내 마켓</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("캠핑장내 마켓이 마련되어있어 언제든 숯, 석쇠, 각종 육류 및 채소, 음료 및 기타식품 등 편의 용품을 편리하게 이용하실 수 있습니다.\r\n");
      out.write("피크닉 지역의 테이블은 90개가 준비되어 있으며 무료 입니다.\r\n");
      out.write("<b>주의</b>: <strong>무료 목재 테이블 1세트 당 그늘막 1동씩만 대여 설치</strong>(그늘막 대여 유료) 하실 수 있습니다. 참조 부탁드립니다.\r\n");
      out.write("    - 추가로 그늘막이나 테이블, 의자가 필요하신 분들은 준비된 물품을 유료로 대여하고 있습니다.\r\n");
      out.write("<strong>대여용품:</strong>이동식 그늘막, 테이블, 의자, 휴대용 가스레인지, 랜턴, 그릴 등\r\n");
      out.write("</pre>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<caption>\r\n");
      out.write("\t\t\t\t<h2>캠프 세팅 메뉴</h2>\r\n");
      out.write("\t\t\t</caption>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<thead align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>식 단</th>\r\n");
      out.write("\t\t\t\t\t\t<th>내 용</th>\r\n");
      out.write("\t\t\t\t\t\t<th>기 타</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tfoot align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>김치찜</th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"2\">1인분(공기밥포함)</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t<tbody align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>돼지고기</td>\r\n");
      out.write("\t\t\t\t\t\t<td>250g</td>\r\n");
      out.write("\t\t\t\t\t\t<td>(녹돈목살)</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>대 하</td>\r\n");
      out.write("\t\t\t\t\t\t<td>수입산</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\">숯불구이</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>소시지</td>\r\n");
      out.write("\t\t\t\t\t\t<td>국내산</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>가래떡</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"3\">인당1개</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>감 자</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>고구마</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>각종야채</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">쌈채소,마늘,오이,고추 등</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<span>인당 1만원 추가시 소고기(등심) 250g 으로 변경 가능</span> <br> <br>\r\n");
      out.write("\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t<thead align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>장 비</td>\r\n");
      out.write("\t\t\t\t\t\t<td>내 용</td>\r\n");
      out.write("\t\t\t\t\t\t<td>기 타</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>그릴(대)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>10인1개</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"3\">번개탄, 숯, 철망, 집게, 가위, 장갑</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>테이블</td>\r\n");
      out.write("\t\t\t\t\t\t<td>10인4테이블</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>의 자</td>\r\n");
      out.write("\t\t\t\t\t\t<td>의자*인원수</td>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<span>입장료와 그늘막은 별도 입니다.</span> <br> <br>\r\n");
      out.write("\t\t\t<h2>주의하실 점</h2>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("이용시 편의를 위해 캠핑장 <strong>출입팔찌</strong>를 드리며 캠핑장 이용이 마무리 되실때까지 착용하고 계시면 캠핑장\r\n");
      out.write("안,밖 출입이 가능합니다. 다만 <b>분실, 미착용 시 입장권을 재 구매</b> 하셔야 하오니 주의해 주시기를 당부드립니다.\r\n");
      out.write("</pre>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("피크닉을 이용하신 경우 별도의 체크아웃 절차없이 익일 <b>오전 09시 30분 까지 퇴영</b>하시면 되며 퇴장 하시기 전\r\n");
      out.write("필히 <strong>대여용품 반납과 쓰레기 정리</strong>를 해주셔야 합니다. <b>시간을 확인 부탁드립니다.</b>\r\n");
      out.write("</pre>\r\n");
      out.write("\r\n");
      out.write("\t\t\t쓰레기는\r\n");
      out.write("\t\t\t<ins>\"규격봉투 (매표소 및 편의점 판매)\"</ins>\r\n");
      out.write("\t\t\t를 사용하셔야 합니다.\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><strong>음식물 쓰레기는 피크닉/캠핑 구역 중간 식수대에 비치된 바구니</strong>에 버려주시면\r\n");
      out.write("\t\t\t\t\t됩니다.</il>\r\n");
      out.write("\t\t\t\t<li>대여물품 반납 후 <b>보증금</b> 혹은 <b>신분증</b>을 찾아 가시면 됩니다.</il>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article id=\"timeNpay\">\r\n");
      out.write("\t\t\t<h1>이용시간 및 요금안내</h1>\r\n");
      out.write("\t\t\t<hr align=\"left\">\r\n");
      out.write("\t\t\t<h2>난지캠핑장 이용시간 및 요금안내</h2>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("이용자분들의 편리한 이용을 위해 아래와 같이 <b>체크인/체크아웃</b> 시간이 정해져 있습니다.\r\n");
      out.write("<br>\r\n");
      out.write("캠핑 또는 피크닉 하시는 분들은 별도의 체크아웃 절차 없이 <b>익일 오전9시30분 퇴영</b> 하시면 됩니다 .\r\n");
      out.write("<br>\r\n");
      out.write("캠핑을 마치신 분들은 퇴장 하시기 전 필히 대여하신 곳에서 용품 반납과 쓰레기 정리를 해주시기 바랍니다.\r\n");
      out.write("쓰레기는 <ins>\"규격봉투 (매표소 및 편의점 판매)\"</ins> 에 담아 캠핑장 용품 대여소 옆 분리수거 장에 버려주시고\r\n");
      out.write("음식물 쓰레기는 각 피크닉/캠핑 구역 중앙에 위치한 식수대에 비치된 바구니에 버려주시면 됩니다.\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t\t<h2>이용시간 안내</h2>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>피크닉 </span>이용자 : <b>오전 10시 30분 부터 체크인</b> / <b>익일\r\n");
      out.write("\t\t\t\t\t\t\t오전 09시 30분 체크아웃</b>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>현장 결제 후 출입증(팔찌교부)</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>피크닉 장소는 지정자리가 아니며 <b>오전 10시 30분 부터</b> 입장 가능합니다.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t(청소 관계로 20분 정도 지연될 수 있습니다. 참조 부탁드립니다.)\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul> <span>캠핑 </span>이용자 : <b>오전 10시 30분 부터 체크인</b> / <b>익일 오전 09시\r\n");
      out.write("\t\t\t\t\t\t\t30분 체크아웃</b>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>예약 확인증을 제출 후 출입증(팔찌교부), 지정자리 사용</li>\r\n");
      out.write("\t\t\t\t\t\t</ul></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<h2>이용요금 안내</h2>\r\n");
      out.write("\t\t\t1인 기준 입장료는 <b>4000원 </b>입니다. 초등학생 이상은 성인 요금이 부과되며 <b>6~7세 2000원,\r\n");
      out.write("\t\t\t\t5세 이하는 무료</b>입니다. <br> <br>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>입장료 할인대상 및 감면 대상</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<pre>\r\n");
      out.write("장애인 등록증 소지자 1~3급은 동반 1인까지 50%할인, 4~6급은 본인만 50%,\r\n");
      out.write("65세 이상이신 분들은 50% 할인 (신분증 확인).\r\n");
      out.write("다둥이 행복카드 소지자는 카드에 등재된 가족에 한해서 50% 할인(<strong>서울지역 해당</strong>).\r\n");
      out.write("국가 유공자 증서 소지하신 분은 본인에 한해 50% 할인.\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t\t<ol type=\"I\">\r\n");
      out.write("\t\t\t\t<li><span>중학생이하</span> 단체할인 (30명 이상)</li>\r\n");
      out.write("\t\t\t\t<li>캠핑을 위한 캠핑장은 \"<mark>B구역과 D구역</mark>\" 으로 나누어 집니다.<br> (<span>이용안내의\r\n");
      out.write("\t\t\t\t\t\t텐트 숙영지 위치를 참조</span>하시고 해당 지역을 <span>예약</span> 하시면 됩니다.)\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>이용요금 안내 가이드</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<ol type=\"I\">\r\n");
      out.write("\t\t\t\t<li>자가텐트 23000원 [입장료 4인 + 전기] 포함</li>\r\n");
      out.write("\t\t\t\t<li>4인용 가족텐트 33000원 [입장료 4인 + 매트] 포함</li>\r\n");
      out.write("\t\t\t\t<li>6인용 캐빈텐트 45000원 [입장료 6인 + 매트] 포함</li>\r\n");
      out.write("\t\t\t\t<li><span>냉.난방 설치된 텐트는 18000원 추가</span></li>\r\n");
      out.write("\t\t\t\t<li>주차요금\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li>시간당 최초 30분에 1000원, 10분에 200원씩 입니다.<br> 이용객은 출차 시\r\n");
      out.write("\t\t\t\t\t\t\t무인카드 정산기에 주차 할인권(매표소에 비치)을 넣으시면 50% 할인 가능합니다.<br> <strong>주차장은\r\n");
      out.write("\t\t\t\t\t\t\t\t한강공원 공영 주차장이며 캠핑장과는 별도로 운영 됩니다.</strong>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article id=\"tip\">\r\n");
      out.write("\t\t\t<h1>준수사항 및 팁</h1>\r\n");
      out.write("\t\t\t<hr align=\"left\">\r\n");
      out.write("\t\t\t<h2>캠핑장이용 준수사항 & 팁 안내</h2>\r\n");
      out.write("\t\t\t<p>난지 캠핑장은 편리하고 쾌적한 이용을 위해 다음의 몇가지 준수 사항을 제시하고 있습니다.</p>\r\n");
      out.write("\t\t\t<ol type=\"1\">\r\n");
      out.write("\t\t\t\t<li><span>캠핑장 이용시간 안내</span><br> 난지 캠핑장의 이용시간은 다음과 같습니다.\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>피크닉(오전 10시 30분)</li>\r\n");
      out.write("\t\t\t\t\t\t<li>캠핑(오전 10시 30분) 부터 익일 오전 09시 30분 까지 입니다.\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>입장권 팔찌안내</span><br> 캠핑장 출입 시 매표소에서 받으신 입장권 팔찌를 꼭\r\n");
      out.write("\t\t\t\t\t착용하여 주시기 바랍니다.<br> <strong>팔찌 미 착용 시 출입이 제한</strong> 되오며 입장권을\r\n");
      out.write("\t\t\t\t\t재 구매 하셔야 합니다.</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>금지행위 안내</span><br> 인라인 스케이트, 보드, 자전거 등 탈것의 운행금지<br>\r\n");
      out.write("\t\t\t\t\t축구, 야구 등 타인에게 피해가 되는 운동 금지<br> 텐트의 실내 탁자 등에 화기 사용 금지<br>\r\n");
      out.write("\t\t\t\t\t음주가무 등으로 인한 소란행위 금지 / 캠프파이어, 폭죽놀이 금지</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>애완동물 동반안내</span><br> 캠핑장 내 애완동물 의 출입은 엄격히 <strong>금지</strong>되고\r\n");
      out.write("\t\t\t\t\t있습니다.</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>식수대 사용안내</span><br> 식수대는 취사를 위해 마련된 장소 입니다. <strong>세면,\r\n");
      out.write("\t\t\t\t\t\t세족 등은 캠프장내 샤워장</strong>을 반드시 이용<br> 해 주시길 바랍니다.</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>LPG가스용기 반입금지 안내</span><br> <strong>LPG가스\r\n");
      out.write("\t\t\t\t\t\t및 프로판가스</strong>반입과 사용이 금지되고 있습니다. (휴대용 부탄가스는 가능)</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>사용금지 전기용품 안내</span><br> <strong>전기포트,\r\n");
      out.write("\t\t\t\t\t\t라디에이터, 전기밥솥, 냉장 및 냉동장치</strong> 등 \"전기 사용량이 큰 제품\" 은 사용이 금지되고 있습니다.</br> (전기사용량 최대\r\n");
      out.write("\t\t\t\t\t500w까지 이용가능, <b>추가 이용시 전기 차단</b>됩니다.)</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>캠핑장 내 영업행위금지 안내</span><br> 캠핑장 내 영업행위가 금지되어\r\n");
      out.write("\t\t\t\t\t있습니다. (외부 출장뷔페 및 생맥주 기계반입 금지)</li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<li><span>타프설치 불가 안내</span><br> 모든 텐트지역 및 피크닉 지역에는 개인 텐트 및\r\n");
      out.write("\t\t\t\t\t타프 설치가 불가능 합니다.</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container-fluid px-lg-5\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 py-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\r\n");
      out.write("\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Twitter\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Facebook\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Instagram\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Services</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Construction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">House\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tRenovation</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Painting</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Arhictecture\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tDesign</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Staff</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Team</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Careers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Resources</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Security</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Global</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Charts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row mt-md-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t\tLink back to Colorlib can't be removed. Template is licensed\r\n");
      out.write("\t\t\t\t\t\t\t\tunder CC BY 3.0. Copyright &copy;\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ion-ios-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\tLink back to Colorlib can't be removed. Template is licensed\r\n");
      out.write("\t\t\t\t\t\t\t\tunder CC BY 3.0.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"footer-heading\">Request A Quote</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" class=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Your Name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Your Email\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Subject\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"\" id=\"\" cols=\"30\" rows=\"3\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"form-control submit px-3\">Send</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\t<!-- <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=2f5541db0e580532285e4af1bdf6e020&libraries=services\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/daum-map.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
