/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-26 02:51:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.myteamproject.model.InfoDAO;
import com.myteamproject.model.InfoTO;

public final class page1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.myteamproject.model.InfoTO");
    _jspx_imports_classes.add("com.myteamproject.model.InfoDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head profile=\"http://www.w3.org/2005/10/profile\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"http://example.com/myicon.png\">\r\n");
      out.write("<title>camper.page1</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/myapp/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h1 {\r\n");
      out.write("\tcolor: #FFBF00\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section {\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".aside {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 15%;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("\t/* width: 50%; */\r\n");
      out.write("}\r\n");
      out.write("#floatMenu {\r\n");
      out.write("position: absolute;\r\n");
      out.write("\tleft: 1500px;\r\n");
      out.write("\ttop: 700px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t// 기존 css에서 플로팅 배너 위치(top)값을 가져와 저장한다.\r\n");
      out.write("\tvar floatPosition = parseInt($(\"#floatMenu\").css('top'));\r\n");
      out.write("\t// 250px 이런식으로 가져오므로 여기서 숫자만 가져온다. parseInt( 값 );\r\n");
      out.write("\r\n");
      out.write("\t$(window).scroll(function() {\r\n");
      out.write("\t\t// 현재 스크롤 위치를 가져온다.\r\n");
      out.write("\t\tvar scrollTop = $(window).scrollTop();\r\n");
      out.write("\t\tvar newPosition = scrollTop + floatPosition + \"px\";\r\n");
      out.write("\r\n");
      out.write("\t\t/* 애니메이션 없이 바로 따라감\r\n");
      out.write("\t\t $(\"#floatMenu\").css('top', newPosition);\r\n");
      out.write("\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#floatMenu\").stop().animate({\r\n");
      out.write("\t\t\t\"top\" : newPosition\r\n");
      out.write("\t\t}, 500);\r\n");
      out.write("\r\n");
      out.write("\t}).scroll();\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#floatMenu\").stop().animate({\r\n");
      out.write("\t\"top\" : newPosition\r\n");
      out.write("}, {\r\n");
      out.write("\t'duration' : 500,\r\n");
      out.write("\t'easing' : 'easeInOutCubic',\r\n");
      out.write("\t'complete' : function() {\r\n");
      out.write("\t\tconsole.log('이동 완료하였습니다.');\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("   </script> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container pt-5\" id=\"upper\">\r\n");
      out.write("\t\t<div class=\"row justify-content-between\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><section style=\"width: 200px; height: 116px; background-image: url('/myapp/resources/images/head.jpg');\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col d-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t<div class=\"social-media\">\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0 d-flex\">Login</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\t\tid=\"ftco-navbar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"fa fa-bars\"></span> Menu\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<form action=\"#\" class=\"searchform order-lg-last\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group d-flex\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control pl-3\" placeholder=\"검색\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" placeholder=\"\" class=\"form-control search\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-search\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"home\" class=\"nav-link\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page2\" class=\"nav-link\">둘러보기</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page3\" class=\"nav-link\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page4\" class=\"nav-link\">예약 및 대여</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page5\" class=\"nav-link\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"page99\" class=\"nav-link\">관리자</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("\t\tstyle=\"background-image: url('/myapp/resources/images/campmain.PNG');\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row no-gutters slider-text align-items-end\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("\t\t\t\t\t<p class=\"breadcrumbs mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mr-2\"><a href=\"index.html\">메인 <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-arrow-forward\"></i></a></span> <span>공지사항 <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ion-ios-arrow-forward\"></i></span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-0 bread\">공지사항</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<nav class=\"nav\">nav</nav>\r\n");
      out.write("\t<aside class=\"aside\">aside\t\r\n");
      out.write("\t<ul id=\"floatMenu\">\r\n");
      out.write("\t\t\t<li><a href=\"#upper\"><div style=\"color:black; text-align:center; width:186px; height: 43px; background-image: url('/myapp/resources/images/sidebutton.gif')\"><strong>공지사항</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#campinfo\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/sidebutton.gif')\"><strong>위치안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#pikinfo\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/sidebutton.gif')\"><strong>피크닉 이용안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#timeNpay\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/sidebutton.gif')\"><strong>이용시간 및 요금안내</strong></div></a></li>\r\n");
      out.write("            <li><a href=\"#tip\"><div style=\"color:black; text-align:center; width: 186px; height: 43px; background-image: url('/myapp/resources/images/sidebutton.gif')\"><strong>준수사항 및 팁</strong></div></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("\t<section class=\"section\">\r\n");
      out.write("\t\t<article id=\"campinfo\">\r\n");
      out.write("\t\t\t<h1>위치안내</h1>\r\n");
      out.write("\t\t\t<hr align=\"left\">\r\n");
      out.write("\t\t\t<h2>찾아오시는 길</h2>\r\n");
      out.write("\t\t\t<div id=\"map\" style=\"width:1000px;height:600px;\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=55d3be58cafbcaf6d4b6320850fcac1f\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\tcenter: new kakao.maps.LatLng(33.450701, 126.570667),\r\n");
      out.write("\t\t\tlevel: 3\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\t</script>\t\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 169px; height: 137px; background-image: url('/myapp/resources/images/map.PNG');\"></td>\r\n");
      out.write("\t\t\t<td><strong>Camper 캠핑장</strong><br>\r\n");
      out.write("\t\t\t주소 :  (153-759) 서울시 금천구 가산동 426-5 월드메르디앙 2차<br>\r\n");
      out.write("\t\t\tTel : 02-2025-8523 ㅣ 상담시간 : 09:00 ~ 18:00\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h2>대중교통안내</h2>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 169px; height: 137px; background-image: url('/myapp/resources/images/sub.PNG');\"></td>\r\n");
      out.write("\t\t\t<td><strong>도시철도</strong><br>\r\n");
      out.write("\t\t\t7호선, 1호선 하차 후 가산디지털단지역5번 출구에서 353m<br>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 169px; height: 137px; background-image: url('/myapp/resources/images/bus.PNG');\"></td>\r\n");
      out.write("\t\t\t<td><strong>버스</strong><br>\r\n");
      out.write("\t\t\t21번, 571번, 652번, 금천05번(마을) 하차 후 100m<br>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><section\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 169px; height: 137px; background-image: url('/myapp/resources/images/car.PNG');\"></td>\r\n");
      out.write("\t\t\t<td><strong>차량이용</strong><br>\r\n");
      out.write("\t\t\t네이게이션 : 한국소프트웨어인재개발원 입력<br>\r\n");
      out.write("\t\t\t카카오 지도 검색 : 한국소프트웨어인재개발원\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container-fluid px-lg-5\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 py-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\r\n");
      out.write("\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Twitter\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Facebook\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"top\" title=\"Instagram\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ion-logo-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Services</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Construction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">House\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tRenovation</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Painting</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Arhictecture\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tDesign</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Staff</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Team</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Careers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Resources</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Security</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Global</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Charts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"py-1 d-block\">Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row mt-md-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t\tLink back to Colorlib can't be removed. Template is licensed\r\n");
      out.write("\t\t\t\t\t\t\t\tunder CC BY 3.0. Copyright &copy;\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ion-ios-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\tLink back to Colorlib can't be removed. Template is licensed\r\n");
      out.write("\t\t\t\t\t\t\t\tunder CC BY 3.0.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"footer-heading\">Request A Quote</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" class=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Your Name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Your Email\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Subject\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"\" id=\"\" cols=\"30\" rows=\"3\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"form-control submit px-3\">Send</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\t<!-- <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=2f5541db0e580532285e4af1bdf6e020&libraries=services\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/daum-map.js\"></script>\r\n");
      out.write("\t<script src=\"/myapp/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
