/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-21 01:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/final_Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1597885521425L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Home Builder - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write(" \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container pt-5\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-between\">\r\n");
      out.write("\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">Home<span>builder.</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col d-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-media\">\r\n");
      out.write("\t\t    \t\t<p class=\"mb-0 d-flex\">\r\n");
      out.write("\t\t    \t\t\t<a href=\"#\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-facebook\"><i class=\"sr-only\">Facebook</i></span></a>\r\n");
      out.write("\t\t    \t\t\t<a href=\"#\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-twitter\"><i class=\"sr-only\">Twitter</i></span></a>\r\n");
      out.write("\t\t    \t\t\t<a href=\"#\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-instagram\"><i class=\"sr-only\">Instagram</i></span></a>\r\n");
      out.write("\t\t    \t\t\t<a href=\"#\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-dribbble\"><i class=\"sr-only\">Dribbble</i></span></a>\r\n");
      out.write("\t\t    \t\t</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t    \r\n");
      out.write("\t      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t        <span class=\"fa fa-bars\"></span> Menu\r\n");
      out.write("\t      </button>\r\n");
      out.write("\t\t\t\t<form action=\"#\" class=\"searchform order-lg-last\">\r\n");
      out.write("          <div class=\"form-group d-flex\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control pl-3\" placeholder=\"Search\">\r\n");
      out.write("            <button type=\"submit\" placeholder=\"\" class=\"form-control search\"><span class=\"fa fa-search\"></span></button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\t      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t        \t<li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">About</a></li>\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"team.html\" class=\"nav-link\">Our team</a></li>\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"project.html\" class=\"nav-link\">Project</a></li>\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("    <div class=\"hero-wrap\">\r\n");
      out.write("\t    <div class=\"home-slider owl-carousel\">\r\n");
      out.write("\t      <div class=\"slider-item\" style=\"background-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_1.jpg);\">\r\n");
      out.write("\t      \t<div class=\"overlay\"></div>\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t          <div class=\"row no-gutters slider-text align-items-center justify-content-center\">\r\n");
      out.write("\t\t          <div class=\"col-md-12 ftco-animate\">\r\n");
      out.write("\t\t          \t<div class=\"text w-100 text-center\">\r\n");
      out.write("\t\t          \t\t<h2>We're here to help you</h2>\r\n");
      out.write("\t\t\t            <h1 class=\"mb-3\">Home Builder</h1>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\r\n");
      out.write("\t      <div class=\"slider-item\" style=\"background-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_2.jpg);\">\r\n");
      out.write("\t      \t<div class=\"overlay\"></div>\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t          <div class=\"row no-gutters slider-text align-items-center justify-content-center\">\r\n");
      out.write("\t\t          <div class=\"col-md-12 ftco-animate\">\r\n");
      out.write("\t\t          \t<div class=\"text w-100 text-center\">\r\n");
      out.write("\t\t          \t\t<h2>Best Builder in the World</h2>\r\n");
      out.write("\t\t\t            <h1 class=\"mb-3\">We Build Home</h1>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\r\n");
      out.write("\t      <div class=\"slider-item\" style=\"background-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_3.jpg);\">\r\n");
      out.write("\t      \t<div class=\"overlay\"></div>\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t          <div class=\"row no-gutters slider-text align-items-center justify-content-center\">\r\n");
      out.write("\t\t          <div class=\"col-md-12 ftco-animate\">\r\n");
      out.write("\t\t          \t<div class=\"text w-100 text-center\">\r\n");
      out.write("\t\t          \t\t<h2>We Build Your Home</h2>\r\n");
      out.write("\t\t\t            <h1 class=\"mb-3\">Professional Builder</h1>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-block text-center pt-md-4\">\r\n");
      out.write("              <div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("            \t\t<span class=\"flaticon-hook\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body p-2 mt-3\">\r\n");
      out.write("                <h3 class=\"heading\">Construction</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-block text-center pt-md-4\">\r\n");
      out.write("              <div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("            \t\t<span class=\"flaticon-skyline\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body p-2 mt-3\">\r\n");
      out.write("                <h3 class=\"heading\">House Renovation</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>    \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-block text-center pt-md-4\">\r\n");
      out.write("              <div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("            \t\t<span class=\"flaticon-stairs\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body p-2 mt-3\">\r\n");
      out.write("                <h3 class=\"heading\">Painting</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-block text-center pt-md-4\">\r\n");
      out.write("              <div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("            \t\t<span class=\"flaticon-home\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body p-2 mt-3\">\r\n");
      out.write("                <h3 class=\"heading\">Architecture Design</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t\t<div class=\"row no-gutters\">\r\n");
      out.write("    \t\t\t<div class=\"col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate\">\r\n");
      out.write("    \t\t\t\t<div class=\"py-3 d-flex\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"flaticon-engineer\"></span>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t<div class=\"text\">\r\n");
      out.write("\t      \t\t\t\t<h3>Expert &amp; Professional</h3>\r\n");
      out.write("\t      \t\t\t\t<p class=\"mb-0\">Separated they live in. A small river named Duden flows</p>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate\">\r\n");
      out.write("    \t\t\t\t<div class=\"py-3 d-flex\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"flaticon-engineer-1\"></span>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t<div class=\"text\">\r\n");
      out.write("\t      \t\t\t\t<h3>High Quality Work</h3>\r\n");
      out.write("\t      \t\t\t\t<p class=\"mb-0\">Separated they live in. A small river named Duden flows</p>\r\n");
      out.write("\t      \t\t\t</div>\r\n");
      out.write("\t      \t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate\">\r\n");
      out.write("    \t\t\t\t<div class=\"py-3 d-flex\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"flaticon-engineer-2\"></span>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t<div class=\"text\">\r\n");
      out.write("\t      \t\t\t\t<h3>24/7 Help Support</h3>\r\n");
      out.write("\t      \t\t\t\t<p class=\"mb-0\">Separated they live in. A small river named Duden flows</p>\r\n");
      out.write("\t      \t\t\t</div>\r\n");
      out.write("\t      \t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </section>\r\n");
      out.write("   \t\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"row d-flex no-gutters\">\r\n");
      out.write("    \t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("    \t\t\t\t<div class=\"img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end\" style=\"background-image:url(images/about.jpg);\">\r\n");
      out.write("    \t\t\t\t\t<a href=\"https://vimeo.com/45830194\" class=\"icon-video popup-vimeo d-flex justify-content-center align-items-center\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"icon-play\"></span>\r\n");
      out.write("    \t\t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-6 pl-md-5\">\r\n");
      out.write("    \t\t\t\t<div class=\"row justify-content-start py-5\">\r\n");
      out.write("\t\t          <div class=\"col-md-12 heading-section ftco-animate pl-md-4 py-md-4\">\r\n");
      out.write("\t\t          \t<span class=\"subheading\">Welcome to Home Builder</span>\r\n");
      out.write("\t\t            <h2 class=\"mb-4\">We create and turn into reality</h2>\r\n");
      out.write("\t\t            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t            <div class=\"tabulation-2 mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav nav-pills nav-fill d-md-flex d-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li class=\"nav-item mb-md-0 mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a class=\"nav-link active py-2\" data-toggle=\"tab\" href=\"#home1\">Our Mission</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li class=\"nav-item px-lg-2 mb-md-0 mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a class=\"nav-link py-2\" data-toggle=\"tab\" href=\"#home2\">Our Vision</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a class=\"nav-link py-2 mb-md-0 mb-2\" data-toggle=\"tab\" href=\"#home3\">Our Value</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab-content bg-light rounded mt-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"tab-pane container p-0 active\" id=\"home1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"tab-pane container p-0 fade\" id=\"home2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"tab-pane container p-0 fade\" id=\"home3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-counter\" id=\"section-counter\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 d-flex\">\r\n");
      out.write("              <div class=\"text d-flex align-items-center\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"50\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-2\">\r\n");
      out.write("              \t<span>Years of <br>Experienced</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 d-flex\">\r\n");
      out.write("              <div class=\"text d-flex align-items-center\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"8500\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-2\">\r\n");
      out.write("              \t<span>Project <br>Done</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 d-flex\">\r\n");
      out.write("              <div class=\"text d-flex align-items-center\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"378\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-2\">\r\n");
      out.write("              \t<span>Professional <br>Expert</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 d-flex\">\r\n");
      out.write("              <div class=\"text d-flex align-items-center\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"1200\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-2\">\r\n");
      out.write("              \t<span>Machineries <br>Equipments</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("\t\t  <div class=\"container-fluid px-md-0\">\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-1.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-1.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-2.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-2.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-3.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-3.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-4.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-4.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-5.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-5.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"work img d-flex align-items-end\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-6.jpg);\">\r\n");
      out.write("            \t<a href=\"images/work-6.jpg\" class=\"icon image-popup d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t    \t\t\t\t\t<span class=\"icon-expand\"></span>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("            \t<div class=\"desc w-100 px-4\">\r\n");
      out.write("\t              <div class=\"text w-100 mb-3\">\r\n");
      out.write("\t              \t<span>Building</span>\r\n");
      out.write("\t              \t<h2><a href=\"work-single.html\">College Health Profession</a></h2>\r\n");
      out.write("\t              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> \r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section testimony-section bg-primary\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5\">\r\n");
      out.write("          <div class=\"col-md-7 text-center heading-section heading-section-white ftco-animate\">\r\n");
      out.write("          \t<span class=\"subheading\">Testimonial</span>\r\n");
      out.write("            <h2 class=\"mb-4\">Happy Clients</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row ftco-animate\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"carousel-testimony owl-carousel ftco-owl\">\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                \t<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    \t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg)\"></div>\r\n");
      out.write("                    \t<div class=\"pl-3\">\r\n");
      out.write("\t\t                    <p class=\"name\">Roger Scott</p>\r\n");
      out.write("\t\t                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                \t<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    \t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_2.jpg)\"></div>\r\n");
      out.write("                    \t<div class=\"pl-3\">\r\n");
      out.write("\t\t                    <p class=\"name\">Roger Scott</p>\r\n");
      out.write("\t\t                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                \t<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    \t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_3.jpg)\"></div>\r\n");
      out.write("                    \t<div class=\"pl-3\">\r\n");
      out.write("\t\t                    <p class=\"name\">Roger Scott</p>\r\n");
      out.write("\t\t                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                \t<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    \t<div class=\"user-img\" style=\"background-image: url(images/person_1.jpg)\"></div>\r\n");
      out.write("                    \t<div class=\"pl-3\">\r\n");
      out.write("\t\t                    <p class=\"name\">Roger Scott</p>\r\n");
      out.write("\t\t                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                \t<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    \t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_2.jpg)\"></div>\r\n");
      out.write("                    \t<div class=\"pl-3\">\r\n");
      out.write("\t\t                    <p class=\"name\">Roger Scott</p>\r\n");
      out.write("\t\t                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section text-center ftco-animate\">\r\n");
      out.write("          \t<span class=\"subheading\">Our Blog</span>\r\n");
      out.write("            <h2>Recent Blog</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row d-flex\">\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/image_1.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text mt-3 text-center\">\r\n");
      out.write("              \t<div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">January 30, 2020</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/image_2.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text mt-3 text-center\">\r\n");
      out.write("              \t<div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">January 30, 2020</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/image_3.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text mt-3 text-center\">\r\n");
      out.write("              \t<div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">January 30, 2020</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pb ftco-no-pt mb-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("      \t<div class=\"row\">\r\n");
      out.write("\t      \t<div class=\"col-md-12\">\r\n");
      out.write("\t      \t\t<div class=\"bg-primary w-100 rounded px-md-0 px-4\">\r\n");
      out.write("\t\t\t        <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("\t\t\t        \t<div class=\"col-lg-8 py-4\">\r\n");
      out.write("\t\t\t        \t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t          <div class=\"col-md-6 d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t            <h2 class=\"mb-0\" style=\"color:white; font-size: 24px;\">Subcribe to our Newsletter</h2>\r\n");
      out.write("\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t          <div class=\"col-md-6 d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t            <form action=\"#\" class=\"subscribe-form\">\r\n");
      out.write("\t\t\t\t\t              <div class=\"form-group d-flex\">\r\n");
      out.write("\t\t\t\t\t                <input type=\"text\" class=\"form-control\" placeholder=\"Enter email address\">\r\n");
      out.write("\t\t\t\t\t                <input type=\"submit\" value=\"Subscribe\" class=\"submit px-3\">\r\n");
      out.write("\t\t\t\t\t              </div>\r\n");
      out.write("\t\t\t\t\t            </form>\r\n");
      out.write("\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t          </div>\r\n");
      out.write("\t\t\t          </div>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid px-lg-5\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-9 py-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("\t\t              <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"ion-logo-twitter\"></span></a></li>\r\n");
      out.write("\t\t              <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"ion-logo-facebook\"></span></a></li>\r\n");
      out.write("\t\t              <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"ion-logo-instagram\"></span></a></li>\r\n");
      out.write("\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Services</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Construction</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">House Renovation</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Painting</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Arhictecture Design</a></li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">About</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Staff</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Team</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Careers</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"footer-heading\">Resources</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Security</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Global</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Charts</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\" class=\"py-1 d-block\">Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row mt-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ion-ios-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("\t\t\t\t\t  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"footer-heading\">Request A Quote</h2>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" class=\"contact-form\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Your Email\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Subject\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <textarea name=\"\" id=\"\" cols=\"30\" rows=\"3\" class=\"form-control\" placeholder=\"Message\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("              \t<button type=\"submit\" class=\"form-control submit px-3\">Send</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/home.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
