/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-21 03:37:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>page 4</title>\r\n");
      out.write("<style>\r\n");
      out.write("  ul.topmenu {\r\n");
      out.write("            border-top: 1px solid  ghostwhite;\r\n");
      out.write("            border-bottom: 1px solid ghostwhite;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 2000px;\r\n");
      out.write("              background-color: #555;\r\n");
      out.write("        }\r\n");
      out.write("        .topmenu > li {\r\n");
      out.write("            border: 0px solid blue;\r\n");
      out.write("            width : 200px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            float: left;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 0px 0px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            \r\n");
      out.write("           }\r\n");
      out.write("        \r\n");
      out.write("        .topmenu > li:hover {\r\n");
      out.write("            background-color: green;\r\n");
      out.write("            border-bottom: 2px solid red;\r\n");
      out.write("        }\r\n");
      out.write("      #title,#navi-bar,#sub-navi{\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body{\r\n");
      out.write("        margin:0;\r\n");
      out.write("        }\r\n");
      out.write("      .nextMenu{\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  width: 25%;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("        }\r\n");
      out.write("        #r1 a{\r\n");
      out.write("\r\n");
      out.write("            display: block;\r\n");
      out.write("  color: #000;\r\n");
      out.write("  padding: 8px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        li a:hover {\r\n");
      out.write("            background-color:  #4CAF56;\r\n");
      out.write("              color: white;\r\n");
      out.write("  color: white;\r\n");
      out.write("        }\r\n");
      out.write("           \r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write(" <section id=welcome_Header>\r\n");
      out.write(" \r\n");
      out.write("        <header>\r\n");
      out.write("            <div id=\"page4\"> \r\n");
      out.write("            \r\n");
      out.write("                <h1>캠핑장 예약 및 대여</h1>\r\n");
      out.write("                <ul class=\"topmenu\">\r\n");
      out.write("                    <li id=\"title\"><a>web title</a></li>\r\n");
      out.write("                    <li id=\"navi-bar\"><a>navigation bar</a></li>\r\n");
      out.write("                    <li id=\"sub-navi\"><a>Sub navigation bar</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        </section>\r\n");
      out.write("    \r\n");
      out.write("             <ul class=\"nextMenu\">\r\n");
      out.write("        <li id=\"r1\"><a class=\"res1\" href=\"#sres1\">예약 및 대여 공지사항</a></li>\r\n");
      out.write("        <li id=\"r1\"><a class=\"res2\" href=\"#sres2\">안내 및 예약 대여</a></li>\r\n");
      out.write("        <li id=\"r1\"><a class=\"res3\" href=\"#sres3\">검색</a></li>\r\n");
      out.write("        <li id=\"r1\"><a class=\"res4\" href=\"#sres4\">현황(예약 및 대여)</a></li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
